### ISSUE TITLE
This app does nothing

### ISSUE THREAD

**Issue by Spielmops** [AkaneTan/Symphonica#4] opened 2023-07-08 05:04 UTC
I can install it, can launch it and then nothing. It does not find any of my Quake3-music ...

Spielmops

**Comment by AkaneTan** [comment] 2023-07-08 05:46
Please provide the android version you are using and make sure you have granted the permission for symphonica. Also consider joining our group if you want real time assistance. The link is at the bottom of readme.md.

**Comment by NeeRaj-2401** [comment] 2023-07-08 09:52
@AkaneTan i have tested too and found the same issue,

android 12, realme ui 3.0
and the app asks for no permission, not even in app info

**Comment by AkaneTan** [comment] 2023-07-08 13:20
@NeeRaj-2401 @Spielmops Should be fixed in [this commit](https://github.com/AkaneTan/Symphonica/commit/945f04b26092d8528fbca61c451feaf17bd58d1e), working on my android 12 phones. Can you check it again in release 0.56b?

**Comment by Spielmops** [comment] 2023-07-08 15:08
The app-version ist 0.53b from Fdroid, my OS is LineageOS 19 and the app does not ask for any permission.

Did you read, that I mentioned "Quake3-music"? The reason for that ist the " md3" in the description of the app. Is that real?

Hartmut

Am 8. Juli 2023 07:47:09 MESZ schrieb Akane ***@***.***>:

**Comment by NeeRaj-2401** [comment] 2023-07-08 15:22
@AkaneTan i tried again and it was showing same behaviour as previous

**Comment by AkaneTan** [comment] 2023-07-08 15:47
> The app-version ist 0.53b from Fdroid, my OS is LineageOS 19 and the app does not ask for any permission. Did you read, that I mentioned "Quake3-music"? The reason for that ist the " md3" in the description of the app. Is that real? Hartmut Am 8. Juli 2023 07:47:09 MESZ schrieb Akane ***@***.***>:
> […](#)
> Please provide the android version you are using and make sure you have granted the permission for symphonica. -- Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/AkaneTan/Symphonica/issues/4#issuecomment-1626875583) You are receiving this because you authored the thread. Message ID: ***@***.***>

Hi. Firstly, I have absolutely no idea where you got that 0.53b package from. Symphonica is only released in my telegram group and this repository's GitHub release. I also don't know what is quake3-music. MD3 in the description means "Material Design 3", which is a unified design language and component library by Google. Perhaps you're mis understanding something here. Also if you can't find any music in symphonica in Android 12, make sure you've upgraded your app version to 0.56b which contains backwards compatibility till Android 10.

**Comment by AkaneTan** [comment] 2023-07-08 15:49
> @AkaneTan i tried again and it was showing same behaviour as previous

Are you sure that you're using 0.56b? Perhaps a fresh install would help in this case? Also please send logs if there's any thrown errors.

**Comment by AkaneTan** [comment] 2023-07-08 16:05
@Wahid7852 tested working on Android 12 with 0.56b. closing this issue.

**Comment by NeeRaj-2401** [comment] 2023-07-08 16:06
> Are you sure that you're using 0.56b? Perhaps a fresh install would help in this case? Also please send logs if there's any thrown errors.


@AkaneTan  No such errors, and yes it was fresh install and i was using latest release.

Feel free to ask if u need any help

Or else wait for few minutes i will send screen recording

**Comment by AkaneTan** [comment] 2023-07-08 16:12
> > Are you sure that you're using 0.56b? Perhaps a fresh install would help in this case? Also please send logs if there's any thrown errors.
> 
> @AkaneTan No such errors, and yes it was fresh install and i was using latest release.
> 
> Feel free to ask if u need any help
> 
> Or else wait for few minutes i will send screen recording

Okay. Logcat would help too if there are any.

**Comment by NeeRaj-2401** [comment] 2023-07-08 16:13
Note that the app doesn't even asked me for media permissions

https://github.com/AkaneTan/Symphonica/assets/88180887/567a7709-5c15-4090-b23c-eb0b9d72d097

**Comment by AkaneTan** [comment] 2023-07-08 16:25
> 

You're using 0.53b. Get latest version here https://github.com/AkaneTan/Symphonica/releases/tag/0.56b and try again.

**Closed as completed** 2023-07-08 17:27 UTC
Labels: bug, possibly solved, need confirm

**Comment by NeeRaj-2401** [comment] 2023-07-08 17:31
@AkaneTan it was downloaded from the same location still issue Exists and in settings it is showing 0.53b

If you dont believe i can record from downloading to installation

I assure you that the issue is not irrelevant

**Comment by AkaneTan** [comment] 2023-07-08 17:55
> @AkaneTan it was downloaded from the same location still issue Exists and in settings it is showing 0.53b
> 
> If you dont believe i can record from downloading to installation
> 
> I assure you that the issue is not irrelevant

Ah sorry my bad. I have just reuploaded the newest release. https://github.com/AkaneTan/Symphonica/releases/download/0.56b.hotfix/app-release.apk

**Comment by NeeRaj-2401** [comment] 2023-07-08 18:15
i can confirm that now its working as expected, thanks :) for your response
